### PR TITLE
Add auth and bits

### PR DESCRIPTION
**Pull request by vanillajonathan**
Add 'auth' and 'bits' to config file

### CODE REVIEW

**Comment by rses** [comment]
Are you doing this incrementally? I can't see where the values from the config file is being read :stuck_out_tongue:

**Comment by rses** [comment]
One minor thing - maybe rebase and squash commits - it keeps the history tree a straight line

**Comment by vanillajonathan** [comment]
> Are you doing this incrementally? I can't see where the values from the config file is being read 😛

Yes. 😳
Those were set in commit e64755d1718e8e69ef5f72f48cef9dac042195cb.

> One minor thing - maybe rebase and squash commits - it keeps the history tree a straight line

I don't think it is possible after it was merged. If it is, then please do.

**Comment by rses** [comment]
> I don't think it is possible after it was merged. If it is, then please do.

I meant for future merges :smile:

**Pull request merged**
