### PR TITLE
Format code

### PR DESCRIPTION
**Pull request by vanillajonathan**
Format code using Black.now.sh

### CODE REVIEW

**Comment by rses** [comment]
I think this is a good idea, but perhaps running it without string quotes or prefixes normalization might be better?

**Comment by vanillajonathan** [comment]
Well the point of code Black is that it has no wiggle room, it is a definitive style guide. There is just one code style Black and it is always the way it is, and it is always with string quotes.

The slogan for Black is "The uncompromising Python code formatter.". Black is opinionated so you don't have to be.

https://black.readthedocs.io/en/latest/

> By using Black, you agree to cede control over minutiae of hand-formatting. In return, Black gives you speed, determinism, and freedom from pycodestyle nagging about formatting. You will save time and mental energy for more important matters.
>
> Black makes code review faster by producing the smallest diffs possible. Blackened code looks the same regardless of the project you’re reading. Formatting becomes transparent after a while and you can focus on the content instead.

https://black.readthedocs.io/en/latest/the_black_code_style.html

> Black reformats entire files in place. It is not configurable. It doesn’t take previous formatting into account.

**Comment by rses** [comment]
Well, I prefer single quotes in Python :confused:

**Comment by rses** [comment]
Sorry, I just noticed this - could you run it on the test file as well? That way, it'll be consistent as well. Also, I'll probably add this as part of the build/test so that it fails if there are formatting mistakes.

**Pull request merged**
