### PR TITLE
Migrate from ABI version 1 to ABI version 5

### PR DESCRIPTION
**Pull request by vanillajonathan**

### CODE REVIEW

**Comment by vanillajonathan** [comment]
@rses Is this of interest?

**Comment by rses** [comment]
It definitely is :smile: I've been a bit tied up the past weekend, but will have a look see do it this weekend. Is this blocking you in any way?

**Comment by vanillajonathan** [comment]
No, it is not. Take your time!

**Comment by rses** [comment]
```If not set the default pipe-abi-version is 1. When set to 2, the local-ip-address field is added after the remote-ip-address, the local-ip-address refers to the IP address the question was received on. When set to 3, the real remote IP/subnet is added based on edns-subnet support (this also requires enabling edns-subnet-processing). When set to 4 it sends zone name in AXFR request```

What does ABI version 5 really give the service? Other than being on the latest version?

```The auth field indicates whether this response is authoritative, this is for DNSSEC. The auth field should be set to ‘1’ for data for which the zone itself is authoritative, which includes the SOA record and its own NS records. The auth field should be 0 for NS records which are used for delegation, and also for any glue (A, AAAA) records present for this purpose. Do note that the DS record for a secure delegation should be authoritative!```

Are we doing it for this `auth=1`?

**Comment by vanillajonathan** [comment]
> What does ABI version 5 really give the service? Other than being on the latest version?
Nothing really at this point of time. Yes, it only provides being on the latest version, but which in turn gives you more functionality for possible future extension.

> Are we doing it for this `auth=1`?

No, mainly to be on the latest version, but now you do have the option of `auth` too if you want to use it for anything.

**Pull request merged**
